// Warning: This file is generated by the `plugins-updater` script.
import RequestSizeLimitingImg from "../assets/plugins/kong-inc_request-size-limiting.png";
import AiPromptTemplateImg from "../assets/plugins/kong-inc_ai-prompt-template.png";
import MockingImg from "../assets/plugins/kong-inc_mocking.png";
import SamlImg from "../assets/plugins/kong-inc_saml.png";
import KafkaUpstreamImg from "../assets/plugins/kong-inc_kafka-upstream.png";
import GrpcWebImg from "../assets/plugins/kong-inc_grpc-web.png";
import KeyAuthEncImg from "../assets/plugins/kong-inc_key-auth-enc.png";
import JweDecryptImg from "../assets/plugins/kong-inc_jwe-decrypt.png";
import OpenwhiskImg from "../assets/plugins/kong-inc_openwhisk.png";
import UpstreamTimeoutImg from "../assets/plugins/kong-inc_upstream-timeout.png";
import RouteTransformerAdvancedImg from "../assets/plugins/kong-inc_route-transformer-advanced.png";
import ForwardProxyImg from "../assets/plugins/kong-inc_forward-proxy.png";
import AclImg from "../assets/plugins/kong-inc_acl.png";
import AiRateLimitingAdvancedImg from "../assets/plugins/kong-inc_ai-rate-limiting-advanced.png";
import ResponseTransformerAdvancedImg from "../assets/plugins/kong-inc_response-transformer-advanced.png";
import HttpLogImg from "../assets/plugins/kong-inc_http-log.png";
import LdapAuthImg from "../assets/plugins/kong-inc_ldap-auth.png";
import ResponseRatelimitingImg from "../assets/plugins/kong-inc_response-ratelimiting.png";
import SessionImg from "../assets/plugins/kong-inc_session.png";
import StatsdImg from "../assets/plugins/kong-inc_statsd.png";
import CorrelationIdImg from "../assets/plugins/kong-inc_correlation-id.png";
import VaultAuthImg from "../assets/plugins/kong-inc_vault-auth.png";
import AiRequestTransformerImg from "../assets/plugins/kong-inc_ai-request-transformer.png";
import RequestValidatorImg from "../assets/plugins/kong-inc_request-validator.png";
import GrpcGatewayImg from "../assets/plugins/kong-inc_grpc-gateway.png";
import FileLogImg from "../assets/plugins/kong-inc_file-log.png";
import Oauth2IntrospectionImg from "../assets/plugins/kong-inc_oauth2-introspection.png";
import TlsHandshakeModifierImg from "../assets/plugins/kong-inc_tls-handshake-modifier.png";
import RequestTransformerImg from "../assets/plugins/kong-inc_request-transformer.png";
import LdapAuthAdvancedImg from "../assets/plugins/kong-inc_ldap-auth-advanced.png";
import BasicAuthImg from "../assets/plugins/kong-inc_basic-auth.png";
import SyslogImg from "../assets/plugins/kong-inc_syslog.png";
import ProxyCacheImg from "../assets/plugins/kong-inc_proxy-cache.png";
import ApplicationRegistrationImg from "../assets/plugins/kong-inc_application-registration.png";
import GraphqlProxyCacheAdvancedImg from "../assets/plugins/kong-inc_graphql-proxy-cache-advanced.png";
import AwsLambdaImg from "../assets/plugins/kong-inc_aws-lambda.png";
import ProxyCacheAdvancedImg from "../assets/plugins/kong-inc_proxy-cache-advanced.png";
import ResponseTransformerImg from "../assets/plugins/kong-inc_response-transformer.png";
import MtlsAuthImg from "../assets/plugins/kong-inc_mtls-auth.png";
import PostFunctionImg from "../assets/plugins/kong-inc_post-function.png";
import PrometheusImg from "../assets/plugins/kong-inc_prometheus.png";
import OktaImg from "../assets/plugins/okta_okta.png";
import WebsocketValidatorImg from "../assets/plugins/kong-inc_websocket-validator.png";
import OasValidationImg from "../assets/plugins/kong-inc_oas-validation.png";
import StatsdAdvancedImg from "../assets/plugins/kong-inc_statsd-advanced.png";
import LogglyImg from "../assets/plugins/kong-inc_loggly.png";
import GraphqlRateLimitingAdvancedImg from "../assets/plugins/kong-inc_graphql-rate-limiting-advanced.png";
import AiPromptDecoratorImg from "../assets/plugins/kong-inc_ai-prompt-decorator.png";
import ExitTransformerImg from "../assets/plugins/kong-inc_exit-transformer.png";
import ImpAppsecConnectorImg from "../assets/plugins/imperva_imp-appsec-connector.png";
import TlsMetadataHeadersImg from "../assets/plugins/kong-inc_tls-metadata-headers.png";
import ZipkinImg from "../assets/plugins/kong-inc_zipkin.png";
import TcpLogImg from "../assets/plugins/kong-inc_tcp-log.png";
import CanaryImg from "../assets/plugins/kong-inc_canary.png";
import RateLimitingImg from "../assets/plugins/kong-inc_rate-limiting.png";
import JqImg from "../assets/plugins/kong-inc_jq.png";
import Oauth2Img from "../assets/plugins/kong-inc_oauth2.png";
import AiProxyImg from "../assets/plugins/kong-inc_ai-proxy.png";
import RouteByHeaderImg from "../assets/plugins/kong-inc_route-by-header.png";
import BotDetectionImg from "../assets/plugins/kong-inc_bot-detection.png";
import KeyAuthImg from "../assets/plugins/kong-inc_key-auth.png";
import OpenidConnectImg from "../assets/plugins/kong-inc_openid-connect.png";
import JwtImg from "../assets/plugins/kong-inc_jwt.png";
import AppDynamicsImg from "../assets/plugins/kong-inc_app-dynamics.png";
import OpentelemetryImg from "../assets/plugins/kong-inc_opentelemetry.png";
import OpaImg from "../assets/plugins/kong-inc_opa.png";
import UdpLogImg from "../assets/plugins/kong-inc_udp-log.png";
import PreFunctionImg from "../assets/plugins/kong-inc_pre-function.png";
import AiPromptGuardImg from "../assets/plugins/kong-inc_ai-prompt-guard.png";
import RequestTransformerAdvancedImg from "../assets/plugins/kong-inc_request-transformer-advanced.png";
import AiAzureContentSafetyImg from "../assets/plugins/kong-inc_ai-azure-content-safety.png";
import DegraphqlImg from "../assets/plugins/kong-inc_degraphql.png";
import DatadogImg from "../assets/plugins/kong-inc_datadog.png";
import HmacAuthImg from "../assets/plugins/kong-inc_hmac-auth.png";
import RateLimitingAdvancedImg from "../assets/plugins/kong-inc_rate-limiting-advanced.png";
import JwtSignerImg from "../assets/plugins/kong-inc_jwt-signer.png";
import IpRestrictionImg from "../assets/plugins/kong-inc_ip-restriction.png";
import AcmeImg from "../assets/plugins/kong-inc_acme.png";
import AzureFunctionsImg from "../assets/plugins/kong-inc_azure-functions.png";
import WebsocketSizeLimitImg from "../assets/plugins/kong-inc_websocket-size-limit.png";
import RequestTerminationImg from "../assets/plugins/kong-inc_request-termination.png";
import CorsImg from "../assets/plugins/kong-inc_cors.png";
import XmlThreatProtectionImg from "../assets/plugins/kong-inc_xml-threat-protection.png";
import KafkaLogImg from "../assets/plugins/kong-inc_kafka-log.png";
import AiResponseTransformerImg from "../assets/plugins/kong-inc_ai-response-transformer.png";

export {
KafkaUpstreamImg,
ExitTransformerImg,
XmlThreatProtectionImg,
PrometheusImg,
KafkaLogImg,
OpaImg,
JwtImg,
HmacAuthImg,
AzureFunctionsImg,
AiAzureContentSafetyImg,
SamlImg,
MtlsAuthImg,
LdapAuthImg,
OpenidConnectImg,
JqImg,
PostFunctionImg,
ResponseTransformerImg,
GraphqlRateLimitingAdvancedImg,
FileLogImg,
OktaImg,
OpentelemetryImg,
ProxyCacheImg,
RouteByHeaderImg,
AiPromptDecoratorImg,
AclImg,
PreFunctionImg,
OasValidationImg,
LdapAuthAdvancedImg,
GrpcWebImg,
Oauth2Img,
StatsdAdvancedImg,
KeyAuthEncImg,
RateLimitingAdvancedImg,
OpenwhiskImg,
ZipkinImg,
AiPromptGuardImg,
HttpLogImg,
CorrelationIdImg,
DegraphqlImg,
TlsHandshakeModifierImg,
UpstreamTimeoutImg,
AiRateLimitingAdvancedImg,
DatadogImg,
ApplicationRegistrationImg,
LogglyImg,
RouteTransformerAdvancedImg,
VaultAuthImg,
RequestTerminationImg,
GrpcGatewayImg,
JwtSignerImg,
ForwardProxyImg,
UdpLogImg,
SessionImg,
ImpAppsecConnectorImg,
IpRestrictionImg,
GraphqlProxyCacheAdvancedImg,
MockingImg,
RequestValidatorImg,
AiResponseTransformerImg,
TcpLogImg,
RequestTransformerAdvancedImg,
AwsLambdaImg,
RequestSizeLimitingImg,
StatsdImg,
SyslogImg,
CorsImg,
KeyAuthImg,
AiPromptTemplateImg,
AppDynamicsImg,
RateLimitingImg,
JweDecryptImg,
ResponseTransformerAdvancedImg,
BasicAuthImg,
AiProxyImg,
WebsocketSizeLimitImg,
CanaryImg,
AcmeImg,
ResponseRatelimitingImg,
AiRequestTransformerImg,
BotDetectionImg,
TlsMetadataHeadersImg,
WebsocketValidatorImg,
Oauth2IntrospectionImg,
ProxyCacheAdvancedImg,
RequestTransformerImg
};