// Warning: This file is generated by the `plugins-updater` script. 
//import AclImg from "@/assets/plugins/kong-inc_acl.png";
import AclImg from "@kong-assets/plugins/kong-inc_acl.png"
import AcmeImg from "@kong-assets/plugins/kong-inc_acme.png";
import AiAzureContentSafetyImg from "@kong-assets/plugins/kong-inc_ai-azure-content-safety.png";
import AiPromptDecoratorImg from "@kong-assets/plugins/kong-inc_ai-prompt-decorator.png";
import AiPromptGuardImg from "@kong-assets/plugins/kong-inc_ai-prompt-guard.png";
import AiPromptTemplateImg from "@kong-assets/plugins/kong-inc_ai-prompt-template.png";
import AiProxyImg from "@kong-assets/plugins/kong-inc_ai-proxy.png";
import AiRateLimitingAdvancedImg from "@kong-assets/plugins/kong-inc_ai-rate-limiting-advanced.png";
import AiRequestTransformerImg from "@kong-assets/plugins/kong-inc_ai-request-transformer.png";
import AiResponseTransformerImg from "@kong-assets/plugins/kong-inc_ai-response-transformer.png";
import AppDynamicsImg from "@kong-assets/plugins/kong-inc_app-dynamics.png";
import ApplicationRegistrationImg from "@kong-assets/plugins/kong-inc_application-registration.png";
import AwsLambdaImg from "@kong-assets/plugins/kong-inc_aws-lambda.png";
import AzureFunctionsImg from "@kong-assets/plugins/kong-inc_azure-functions.png";
import BasicAuthImg from "@kong-assets/plugins/kong-inc_basic-auth.png";
import BotDetectionImg from "@kong-assets/plugins/kong-inc_bot-detection.png";
import CanaryImg from "@kong-assets/plugins/kong-inc_canary.png";
import CorrelationIdImg from "@kong-assets/plugins/kong-inc_correlation-id.png";
import CorsImg from "@kong-assets/plugins/kong-inc_cors.png";
import DatadogImg from "@kong-assets/plugins/kong-inc_datadog.png";
import DegraphqlImg from "@kong-assets/plugins/kong-inc_degraphql.png";
import ExitTransformerImg from "@kong-assets/plugins/kong-inc_exit-transformer.png";
import FileLogImg from "@kong-assets/plugins/kong-inc_file-log.png";
import ForwardProxyImg from "@kong-assets/plugins/kong-inc_forward-proxy.png";
import GraphqlProxyCacheAdvancedImg from "@kong-assets/plugins/kong-inc_graphql-proxy-cache-advanced.png";
import GraphqlRateLimitingAdvancedImg from "@kong-assets/plugins/kong-inc_graphql-rate-limiting-advanced.png";
import GrpcGatewayImg from "@kong-assets/plugins/kong-inc_grpc-gateway.png";
import GrpcWebImg from "@kong-assets/plugins/kong-inc_grpc-web.png";
import HmacAuthImg from "@kong-assets/plugins/kong-inc_hmac-auth.png";
import HttpLogImg from "@kong-assets/plugins/kong-inc_http-log.png";
import ImpAppsecConnectorImg from "@kong-assets/plugins/imperva_imp-appsec-connector.png";
import IpRestrictionImg from "@kong-assets/plugins/kong-inc_ip-restriction.png";
import JqImg from "@kong-assets/plugins/kong-inc_jq.png";
import JweDecryptImg from "@kong-assets/plugins/kong-inc_jwe-decrypt.png";
import JwtImg from "@kong-assets/plugins/kong-inc_jwt.png";
import JwtSignerImg from "@kong-assets/plugins/kong-inc_jwt-signer.png";
import KafkaLogImg from "@kong-assets/plugins/kong-inc_kafka-log.png";
import KafkaUpstreamImg from "@kong-assets/plugins/kong-inc_kafka-upstream.png";
import KeyAuthEncImg from "@kong-assets/plugins/kong-inc_key-auth-enc.png";
import KeyAuthImg from "@kong-assets/plugins/kong-inc_key-auth.png";
import LdapAuthAdvancedImg from "@kong-assets/plugins/kong-inc_ldap-auth-advanced.png";
import LdapAuthImg from "@kong-assets/plugins/kong-inc_ldap-auth.png";
import LogglyImg from "@kong-assets/plugins/kong-inc_loggly.png";
import MockingImg from "@kong-assets/plugins/kong-inc_mocking.png";
import MtlsAuthImg from "@kong-assets/plugins/kong-inc_mtls-auth.png";
import OasValidationImg from "@kong-assets/plugins/kong-inc_oas-validation.png";
import Oauth2Img from "@kong-assets/plugins/kong-inc_oauth2.png";
import Oauth2IntrospectionImg from "@kong-assets/plugins/kong-inc_oauth2-introspection.png";
import OktaImg from "@kong-assets/plugins/okta_okta.png";
import OpaImg from "@kong-assets/plugins/kong-inc_opa.png";
import OpenidConnectImg from "@kong-assets/plugins/kong-inc_openid-connect.png";
import OpentelemetryImg from "@kong-assets/plugins/kong-inc_opentelemetry.png";
import OpenwhiskImg from "@kong-assets/plugins/kong-inc_openwhisk.png";
import PostFunctionImg from "@kong-assets/plugins/kong-inc_post-function.png";
import PreFunctionImg from "@kong-assets/plugins/kong-inc_pre-function.png";
import PrometheusImg from "@kong-assets/plugins/kong-inc_prometheus.png";
import ProxyCacheAdvancedImg from "@kong-assets/plugins/kong-inc_proxy-cache-advanced.png";
import ProxyCacheImg from "@kong-assets/plugins/kong-inc_proxy-cache.png";
import RateLimitingAdvancedImg from "@kong-assets/plugins/kong-inc_rate-limiting-advanced.png";
import RateLimitingImg from "@kong-assets/plugins/kong-inc_rate-limiting.png";
import RequestSizeLimitingImg from "@kong-assets/plugins/kong-inc_request-size-limiting.png";
import RequestTerminationImg from "@kong-assets/plugins/kong-inc_request-termination.png";
import RequestTransformerAdvancedImg from "@kong-assets/plugins/kong-inc_request-transformer-advanced.png";
import RequestTransformerImg from "@kong-assets/plugins/kong-inc_request-transformer.png";
import RequestValidatorImg from "@kong-assets/plugins/kong-inc_request-validator.png";
import ResponseRatelimitingImg from "@kong-assets/plugins/kong-inc_response-ratelimiting.png";
import ResponseTransformerAdvancedImg from "@kong-assets/plugins/kong-inc_response-transformer-advanced.png";
import ResponseTransformerImg from "@kong-assets/plugins/kong-inc_response-transformer.png";
import RouteByHeaderImg from "@kong-assets/plugins/kong-inc_route-by-header.png";
import RouteTransformerAdvancedImg from "@kong-assets/plugins/kong-inc_route-transformer-advanced.png";
import SamlImg from "@kong-assets/plugins/kong-inc_saml.png";
import SessionImg from "@kong-assets/plugins/kong-inc_session.png";
import StatsdAdvancedImg from "@kong-assets/plugins/kong-inc_statsd-advanced.png";
import StatsdImg from "@kong-assets/plugins/kong-inc_statsd.png";
import SyslogImg from "@kong-assets/plugins/kong-inc_syslog.png";
import TcpLogImg from "@kong-assets/plugins/kong-inc_tcp-log.png";
import TlsHandshakeModifierImg from "@kong-assets/plugins/kong-inc_tls-handshake-modifier.png";
import TlsMetadataHeadersImg from "@kong-assets/plugins/kong-inc_tls-metadata-headers.png";
import UdpLogImg from "@kong-assets/plugins/kong-inc_udp-log.png";
import UpstreamTimeoutImg from "@kong-assets/plugins/kong-inc_upstream-timeout.png";
import VaultAuthImg from "@kong-assets/plugins/kong-inc_vault-auth.png";
import WebsocketSizeLimitImg from "@kong-assets/plugins/kong-inc_websocket-size-limit.png";
import WebsocketValidatorImg from "@kong-assets/plugins/kong-inc_websocket-validator.png";
import XmlThreatProtectionImg from "@kong-assets/plugins/kong-inc_xml-threat-protection.png";
import ZipkinImg from "@kong-assets/plugins/kong-inc_zipkin.png";

export {
AclImg,
AcmeImg,
AiAzureContentSafetyImg,
AiPromptDecoratorImg,
AiPromptGuardImg,
AiPromptTemplateImg,
AiProxyImg,
AiRateLimitingAdvancedImg,
AiRequestTransformerImg,
AiResponseTransformerImg,
AppDynamicsImg,
ApplicationRegistrationImg,
AwsLambdaImg,
AzureFunctionsImg,
BasicAuthImg,
BotDetectionImg,
CanaryImg,
CorrelationIdImg,
CorsImg,
DatadogImg,
DegraphqlImg,
ExitTransformerImg,
FileLogImg,
ForwardProxyImg,
GraphqlProxyCacheAdvancedImg,
GraphqlRateLimitingAdvancedImg,
GrpcGatewayImg,
GrpcWebImg,
HmacAuthImg,
HttpLogImg,
ImpAppsecConnectorImg,
IpRestrictionImg,
JqImg,
JweDecryptImg,
JwtImg,
JwtSignerImg,
KafkaLogImg,
KafkaUpstreamImg,
KeyAuthEncImg,
KeyAuthImg,
LdapAuthAdvancedImg,
LdapAuthImg,
LogglyImg,
MockingImg,
MtlsAuthImg,
OasValidationImg,
Oauth2Img,
Oauth2IntrospectionImg,
OktaImg,
OpaImg,
OpenidConnectImg,
OpentelemetryImg,
OpenwhiskImg,
PostFunctionImg,
PreFunctionImg,
PrometheusImg,
ProxyCacheAdvancedImg,
ProxyCacheImg,
RateLimitingAdvancedImg,
RateLimitingImg,
RequestSizeLimitingImg,
RequestTerminationImg,
RequestTransformerAdvancedImg,
RequestTransformerImg,
RequestValidatorImg,
ResponseRatelimitingImg,
ResponseTransformerAdvancedImg,
ResponseTransformerImg,
RouteByHeaderImg,
RouteTransformerAdvancedImg,
SamlImg,
SessionImg,
StatsdAdvancedImg,
StatsdImg,
SyslogImg,
TcpLogImg,
TlsHandshakeModifierImg,
TlsMetadataHeadersImg,
UdpLogImg,
UpstreamTimeoutImg,
VaultAuthImg,
WebsocketSizeLimitImg,
WebsocketValidatorImg,
XmlThreatProtectionImg,
ZipkinImg
};