import { makeStyles } from "@material-ui/core";
import { themeVariables } from "../../../utils/constants/theme";

export const useMarkdowRendererStyles = makeStyles({
  wrapper: {
    width: "100%",
    maxWidth: "52vw",
    maxHeight: "48vh",
    color: themeVariables.colors.white,
    paddingBottom: "2rem",
    overflowY: "scroll",
    borderBottom: `1px solid ${themeVariables.border.main}`,
    "& h1, h2, h3, h4, h5, h6": {
      color: themeVariables.colors.white,
      margin: "1rem 0",
    },
    "& p": {
      margin: "0.5rem 0",
      lineHeight: "1.6",
      fontSize: "1rem",
    },
    "& a": {
      color: themeVariables.colors.main,
      textDecoration: "none",
      "&:hover": {
        textDecoration: "underline",
      },
    },
    "& ul, & ol": {
      width: "100%",
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-start",
      justifyContent: "center",
      padding: ".9rem",
    },
    "& code": {
      padding: "0.2rem 0.4rem",
      borderRadius: "4px",
      fontFamily: "Roboto Mono, monospace",
      fontSize: "1em",
      lineHeight: "1.5em",
      color: "#eee",
      backgroundColor: "#2f2f2f",
    },
    "& pre": {
      backgroundColor: "#2f2f2f",
      color: "#eee",
      fontFamily: "Roboto Mono, monospace",
      fontSize: "1em",
      lineHeight: "1.5em",
      overflowX: "auto",
      position: "relative",
      margin: "0.5em 0",
      padding: "1.25em 1em",
      borderRadius: "6px",
    },
    "& table": {
      borderCollapse: "collapse",
      width: "100%",
    },
    "& th, & td": {
      border: `1px solid ${themeVariables.border.main}`,
      padding: "0.5rem",
      textAlign: "left",
    },
    "& code[class*='language-']": {
      textAlign: "left",
      whiteSpace: "pre",
      wordSpacing: "normal",
      wordBreak: "normal",
      wordWrap: "normal",
      MozTabSize: "4",
      OTabSize: "4",
      tabSize: "4",
      WebkitHyphens: "none",
      MozHyphens: "none",
      msHyphens: "none",
      hyphens: "none",
    },
    "& pre[class*='language-']": {
      textAlign: "left",
      whiteSpace: "pre",
      wordSpacing: "normal",
      wordBreak: "normal",
      wordWrap: "normal",
      MozTabSize: "4",
      OTabSize: "4",
      tabSize: "4",
      WebkitHyphens: "none",
      MozHyphens: "none",
      msHyphens: "none",
      hyphens: "none",
      overflow: "auto",
      position: "relative",
      margin: "0.5em 0",
      padding: "1.25em 1em",
    },
    "& code[class*='language-']::-moz-selection, & pre[class*='language-']::-moz-selection": {
      background: "#363636",
    },
    "& code[class*='language-']::selection, & pre[class*='language-']::selection": {
      background: "#363636",
    },
    "& :not(pre) > code[class*='language-']": {
      whiteSpace: "normal",
      borderRadius: "0.2em",
      padding: "0.1em",
    },
    "& .language-css > code, & .language-sass > code, & .language-scss > code": {
      color: "#fd9170",
    },
    "& [class*='language-'] .namespace": {
      opacity: "0.7",
    },
    "& .atrule": { color: "#c792ea" },
    "& .attr-name": { color: "#ffcb6b" },
    "& .attr-value": { color: "#a5e844" },
    "& .attribute": { color: "#a5e844" },
    "& .boolean": { color: "#c792ea" },
    "& .builtin": { color: "#ffcb6b" },
    "& .cdata, & .char, & .property": { color: "#80cbc4" },
    "& .class": { color: "#ffcb6b" },
    "& .class-name": { color: "#f2ff00" },
    "& .comment": { color: "#616161" },
    "& .constant, & .function, & .keyword": { color: "#c792ea" },
    "& .deleted, & .entity, & .tag, & .url, & .variable": { color: "#ff6666" },
    "& .doctype, & .prolog": { color: "#616161" },
    "& .inserted": { color: "#80cbc4" },
    "& .number, & .unit": { color: "#fd9170" },
    "& .operator, & .punctuation": { color: "#89ddff" },
    "& .regex, & .hexcode": { color: "#f2ff00" },
    "& .selector": { color: "#ff6666" },
    "& .string, & .pseudo-class, & .pseudo-element": { color: "#a5e844" },
    "& .symbol": { color: "#c792ea" },
    "& .important, & .id": {
      color: "#c792ea",
      fontWeight: "bold",
    },
  },
});
